# -*- coding: utf-8 -*-
"""
/***************************************************************************
 _fabdem
                                 A QGIS plugin
 FABDEM-tile-finder
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-09
        copyright            : (C) 2024 by Christian Milner / SLR
        email                : cmilner@slrconsulting.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load _fabdem class from file _fabdem.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fabdem import _fabdem
    return _fabdem(iface)
